spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/CondoHub
spring.datasource.username=postgres
spring.datasource.password=14022005

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
